# Deep Copy and Shallow Copy

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
import seaborn as sns
warnings.filterwarnings('ignore')

In [2]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [3]:
data_tips = sns.load_dataset('tips')
data_tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [4]:
data_tips_shallow_copy = data_tips

In [5]:
data_tips_shallow_copy

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [6]:
id(data_tips)

2770380265792

In [7]:
id(data_tips_shallow_copy)

2770380265792

In [8]:
data_tips_deep_copy = data_tips.copy()

In [9]:
data_tips_deep_copy

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [10]:
id(data_tips_deep_copy)

2770379013104

In [11]:
data_tips.drop(columns=['time', 'size'], inplace=True)
data_tips

     total_bill   tip     sex smoker   day
0         16.99  1.01  Female     No   Sun
1         10.34  1.66    Male     No   Sun
2         21.01  3.50    Male     No   Sun
3         23.68  3.31    Male     No   Sun
4         24.59  3.61  Female     No   Sun
..          ...   ...     ...    ...   ...
239       29.03  5.92    Male     No   Sat
240       27.18  2.00  Female    Yes   Sat
241       22.67  2.00    Male    Yes   Sat
242       17.82  1.75    Male     No   Sat
243       18.78  3.00  Female     No  Thur

[244 rows x 5 columns]

In [12]:
data_tips_shallow_copy

     total_bill   tip     sex smoker   day
0         16.99  1.01  Female     No   Sun
1         10.34  1.66    Male     No   Sun
2         21.01  3.50    Male     No   Sun
3         23.68  3.31    Male     No   Sun
4         24.59  3.61  Female     No   Sun
..          ...   ...     ...    ...   ...
239       29.03  5.92    Male     No   Sat
240       27.18  2.00  Female    Yes   Sat
241       22.67  2.00    Male    Yes   Sat
242       17.82  1.75    Male     No   Sat
243       18.78  3.00  Female     No  Thur

[244 rows x 5 columns]

In [13]:
data_tips_deep_copy

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]